---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - goodnight-kube.joshmeyer.dev
  resources:
  - goodnightdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - goodnight-kube.joshmeyer.dev
  resources:
  - goodnightdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - goodnight-kube.joshmeyer.dev
  resources:
  - goodnightdeployments/status
  verbs:
  - get
  - patch
  - update
